# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
---
version: 2
updates:
  - package-ecosystem: "cargo"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
    directories: ["/", "/crates/*"]
